version: '3'
services:
  brand-user-authorization-backend:
    build: ./backend/
    ports:
      - 8081:8081
    restart: always
    environment:
      ROLE_FILE: /data/role.json
      USER_FILE: /data/user.json
    volumes:
      - ./backend/data:/data